name: composite example
on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: sureshmusale/hello-world-composite-action@v1
        with:
          who-to-greet: '******SURESH MUSALE*********'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
